#!/usr/bin/env python

import os
import sys
import argparse
import ConfigParser
import gi

gi.require_version('Ufo', '0.0')

from gi.repository import Ufo
from upiv.ufo_extension import TaskGraph, PluginManager
from upiv.ddict import DotDict


ROOT = os.path.abspath('.')


def read_parameters():
    # parse command line arguments
    parser = argparse.ArgumentParser()
    parser.add_argument('-p', '--profiling', action='store_true', default=False)
    parser.add_argument('config', type=str, help="Config file")
    args = parser.parse_args()

    cf_parser = ConfigParser.ConfigParser()

    # parse configuration file
    if cf_parser.read(args.config) != []:
        params = {k: eval(v) for k,v in cf_parser.items('piv')}
        config = {k: eval(v) for k,v in cf_parser.items('config')}
    else:
        print("Unable to open {}".format(args.config))
        sys.exit(-1)

    # overwrite config/params with command line arguments
    if args.profiling:
        config['profiling'] = args.profiling

    return DotDict(params), DotDict(config)


def load_filters(params):
    filters = DotDict({})
    scale = params.scale
    params.ring_number = (params.ring_end - params.ring_start) / params.ring_step

    in_path = os.path.abspath(params.in_path)

    out_imag = params.get('output_img') or 'res.tif'
    out_imag = os.path.join(ROOT, out_imag)

    out_ring = params.get('output_ring') or 'res.txt'
    out_ring = os.path.join(ROOT, out_ring)

    filters['write'] = {
        'property': {
            'filename': out_imag
        }
    }
    filters['ring_writer'] = {
        'property': {
            'filename': out_ring
        }
    }
    filters['read'] = {
        'property': {
            'path': in_path,
            'number': params.number
        }
    }
    filters['crop'] = {
        'property': {
            'x': params.xshift,
            'y': params.yshift,
            'width': params.width,
            'height': params.height
        }
    }
    filters['contrast'] = {
        'name': 'piv_contrast',
        'property': {
            'c1': params.contrast_c1,
            'c2': params.contrast_c2,
            'gamma': params.contrast_gamma
        }
    }
    filters['rescale'] = {
        'property': { 'factor': 1.0/scale }
    }
    filters['input_fft'] = {
        'name': 'fft',
        'property': { 'dimensions' : 2 }
    }
    filters['ring_fft'] = {
        'name': 'fft',
        'property': { 'dimensions' : 2 }
    }
    filters['ring_stack'] = {
        'name': 'stack',
        'property': {'number': params.ring_number}
    }
    filters['bc_image'] = {
        'name': 'broadcast'
    }
    filters['ring_loop'] = {
        'name': 'loop',
        'property': {'number': params.number}
    }
    filters['ring_convolution'] = {
        'name': 'complex_mult'
    }
    filters['ring_slice'] = {
        'name': 'slice'
    }
    filters['ring_pattern'] = {
        'property': {
            'start': params.ring_start/scale,
            'end': params.ring_end/scale,
            'step': params.ring_step/scale,
            'thickness': params.ring_thickness/scale,
            'method': params.ring_method,
            'width': params.width/scale,
            'height': params.height/scale
        }
    }
    filters['ifft'] = {
        'property': { 'dimensions': 2 }
    }
    filters['likelihood'] = {
        'name': 'hough-likelihood',
        'property': {
            'masksize': params.likelihoodmask,
            'maskinnersize': params.likelihoodmaskinner,
            'threshold': params.thld_likely
        }
    }
    filters['candidate'] = {
        'name': 'candidate-filter',
        'property': {
            'ring_start': params.ring_start,
            'ring_step': params.ring_step,
            'ring_end': params.ring_end,
            'scale': params.scale
        }
    }
    filters['azimu'] = {
        'name': 'azimuthal-test',
        'property': {
            'thread': params.threads,
            'azimu_thld': params.thld_azimu,
            'likelihood_thld': params.thld_likely,
        }
    }

    return filters


def main():
    params, config = read_parameters()
    filters = load_filters(params)

    pm = PluginManager()
    g = TaskGraph()

    for k,v in filters.iteritems():
        name = v.get('name') or k
        prop = v.get('property') or {}
        if name is 'broadcast':
            g.tasks[k] = Ufo.CopyTask() 
        else:
            g.tasks[k] = pm.get_task(name)
            g.tasks[k].set_properties(**prop)

    b1 = g.branch('read', 'crop', 'contrast', 'bc_image', 'rescale', 'input_fft')
    b2 = g.branch('ring_pattern', 'ring_stack', 'ring_fft', 'ring_loop')
    b3 = g.branch('bc_image')
    b4 = g.branch('ring_convolution', 'ifft', 'likelihood', 'candidate')
    b5 = g.branch('azimu', 'ring_writer')

    g.merge_branch(b1, b2, b4)
    g.merge_branch(b3, b4, b5)

    sched = Ufo.FixedScheduler()
    sched.set_properties(enable_tracing=False)
    sched.run(g)


if __name__ == '__main__':
    main()
